services:
  - type: web
    name: bamblu-api
    runtime: node
    plan: free

    buildCommand: |
      corepack prepare yarn@4.5.3 --activate
      corepack yarn install --immutable

      cd apps/api

      echo "===== Running Prisma generate ====="
      npx prisma generate

      echo "===== Running Prisma migrate deploy ====="
      npx prisma migrate deploy

      echo "===== Building NestJS ====="
      yarn build

    startCommand: node dist/main.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: API_URL
        sync: false
      - key: WEB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: CODEFORCES_API_KEY
        sync: false
      - key: CODEFORCES_API_SECRET
        sync: false
