services:
  - type: web
    name: bamblu-api
    runtime: node
    buildCommand: |
      corepack prepare yarn@4.5.3 --activate
      corepack yarn install --immutable

      cd apps/api

      echo "=== Before generate ==="
      ls -R src/generated || true

      npx prisma generate

      echo "=== After generate ==="
      ls -R src/generated

      yarn build
    startCommand: node apps/api/dist/main.js